#!/usr/bin/env python2

import sys
import os
import glob

# extract filename and version number from command line input
if (len(sys.argv) == 3):
    filename = sys.argv[1]
    versionNum = int(sys.argv[2])
else :
    print 'Enter a single filename and version number as input'
    exit()

versionPath = os.getcwd() + '/.versiondir/.' + filename

# find all the versions of the file
versions = sorted(glob.glob(versionPath + '*'))

# an invalid version number has been entered
if (len(versions) < versionNum):
    print 'Sorry, this version doesn\'t exist'
    exit()

catVersion = open(versions[versionNum-1], 'r')
print(catVersion.read())
