#!/usr/bin/env python2

import glob
import os
import sys
import re

from shutil import copy2

# extract filename and version number from command line input
if (len(sys.argv) == 3):
    filename = sys.argv[1]
    versionNum = int(sys.argv[2])
# user has not supplied enough arguments
else :
    print 'Enter a single filename and version number as input'
    exit()

versionPath = os.getcwd() + '/.versiondir/.' + filename

# find all the versions of the current file
versions = sorted(glob.glob(versionPath + '.*'))

# store the version to update to in a temporary file if version exists
if (len(versions) >= versionNum):
    curVersion = versions[versionNum -1]
    copy2(curVersion, versionPath + '_tmp')
else :
    print 'Sorry, this version does not exist'

# sort the versions from oldest to newest
versions.reverse()

# delete the oldest version to make room for new version
if (len(versions) == 6):
    oldest = versions.pop(0)
    os.remove(oldest)

# increment the version number for each version
for version in versions:
    # extract version number from filename
    ints = re.findall(r'\d+', version)
    versionNum = ints[len(ints) - 1] 

    # increment version number
    newVersionNum = int(versionNum) + 1
    os.rename(version, versionPath + '.' + str(newVersionNum))

# most recent version is now the requested previous version
copy2(versionPath + '_tmp', versionPath + '.1')
os.remove(versionPath + '_tmp')