#!/usr/bin/env python2

# upi: mbea966
# name: Madeleine Beagley

import glob
import os
import sys

# extract filename from command line input
if (len(sys.argv) == 2):
    filename = sys.argv[1]
# user has not supplied sufficient arguments
else :
    print 'Enter a single filename as input'
    exit()

versionPath = os.getcwd() + '/.versiondir/.' + filename

# find all versions of the file
versions = sorted(glob.glob(versionPath + '*'))

# remove all versions of the input file except for the most recent
for version in versions[1:]:
    os.remove(version)