#!/bin/bash

# remove regular files from directories
rm -rf .versiondir/* mount/*

# remove hidden files from directories and redirect error messages
rm -rf .versiondir/.* mount/.* 2> /dev/null

# remove compiled fuse file
rm fuse.pyc

# shut down mounting system
fusermount -u mount